<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260521110010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE antecedent DROP CONSTRAINT fk_3166be7cf531f4c5');
        $this->addSql('DROP TABLE antecedent');
        $this->addSql('ALTER TABLE dossier_medical ADD antecedents_medicaux TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical DROP antecedents');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE antecedent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_3166be7cf531f4c5 ON antecedent (hospitalisation_id)');
        $this->addSql('ALTER TABLE antecedent ADD CONSTRAINT fk_3166be7cf531f4c5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE dossier_medical ADD antecedents JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical DROP antecedents_medicaux');
    }
}
