<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260327141223 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bon_matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, type VARCHAR(255) NOT NULL, motif VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_bon TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reference_externe VARCHAR(255) DEFAULT NULL, observation TEXT DEFAULT NULL, impact_stock BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ordonnateur_id INT DEFAULT NULL, cree_par_id INT DEFAULT NULL, vente_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_560CF280F55AE19E ON bon_matiere (numero)');
        $this->addSql('CREATE INDEX IDX_560CF28057F601D5 ON bon_matiere (ordonnateur_id)');
        $this->addSql('CREATE INDEX IDX_560CF280FC29C013 ON bon_matiere (cree_par_id)');
        $this->addSql('CREATE INDEX IDX_560CF2807DC7170A ON bon_matiere (vente_id)');
        $this->addSql('CREATE TABLE bon_matiere_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION DEFAULT NULL, observation TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bon_id INT NOT NULL, medicament_id INT NOT NULL, lot_id INT DEFAULT NULL, vente_ligne_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D36BCD40AD65737C ON bon_matiere_ligne (bon_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40AB0D61F7 ON bon_matiere_ligne (medicament_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40A8CBA5F7 ON bon_matiere_ligne (lot_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40FA166692 ON bon_matiere_ligne (vente_ligne_id)');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF28057F601D5 FOREIGN KEY (ordonnateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF280FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF2807DC7170A FOREIGN KEY (vente_id) REFERENCES vente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40AD65737C FOREIGN KEY (bon_id) REFERENCES bon_matiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40AB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40FA166692 FOREIGN KEY (vente_ligne_id) REFERENCES vente_ligne (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier_medical ADD groupe_sanguin VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD allergies TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD antecedents_medicaux TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD antecedents_chirurgicaux TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD maladies_chroniques TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD traitement_en_cours TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD handicap VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE dossier_medical ADD grossesse BOOLEAN DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF28057F601D5');
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF280FC29C013');
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF2807DC7170A');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40AD65737C');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40AB0D61F7');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40A8CBA5F7');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40FA166692');
        $this->addSql('DROP TABLE bon_matiere');
        $this->addSql('DROP TABLE bon_matiere_ligne');
        $this->addSql('ALTER TABLE dossier_medical DROP groupe_sanguin');
        $this->addSql('ALTER TABLE dossier_medical DROP allergies');
        $this->addSql('ALTER TABLE dossier_medical DROP antecedents_medicaux');
        $this->addSql('ALTER TABLE dossier_medical DROP antecedents_chirurgicaux');
        $this->addSql('ALTER TABLE dossier_medical DROP maladies_chroniques');
        $this->addSql('ALTER TABLE dossier_medical DROP traitement_en_cours');
        $this->addSql('ALTER TABLE dossier_medical DROP handicap');
        $this->addSql('ALTER TABLE dossier_medical DROP grossesse');
    }
}
