<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260413074649 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE convention_prise_en_charge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_prestation VARCHAR(255) NOT NULL, taux_couverture INT NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, observation TEXT DEFAULT NULL, organisme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1A0B6F1C5DDD38F5 ON convention_prise_en_charge (organisme_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_organisme_type_prestation ON convention_prise_en_charge (organisme_id, type_prestation)');
        $this->addSql('CREATE TABLE organisme_prise_en_charge (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(150) NOT NULL, code VARCHAR(50) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, description TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6F2E35E06C6E55B5 ON organisme_prise_en_charge (nom)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_6F2E35E077153098 ON organisme_prise_en_charge (code)');
        $this->addSql('CREATE TABLE patient_couverture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_assure VARCHAR(100) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, date_debut DATE DEFAULT NULL, date_fin DATE DEFAULT NULL, observation TEXT DEFAULT NULL, patient_id INT NOT NULL, organisme_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CAD57BEF6B899279 ON patient_couverture (patient_id)');
        $this->addSql('CREATE INDEX IDX_CAD57BEF5DDD38F5 ON patient_couverture (organisme_id)');
        $this->addSql('ALTER TABLE convention_prise_en_charge ADD CONSTRAINT FK_1A0B6F1C5DDD38F5 FOREIGN KEY (organisme_id) REFERENCES organisme_prise_en_charge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_couverture ADD CONSTRAINT FK_CAD57BEF6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE patient_couverture ADD CONSTRAINT FK_CAD57BEF5DDD38F5 FOREIGN KEY (organisme_id) REFERENCES organisme_prise_en_charge (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facture ADD montant_total_brut INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture ADD montant_total_prise_en_charge INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture ADD montant_total_patient INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture ADD montant_paye_patient INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture ADD reste_patient INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture ADD prise_en_charge_active BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE facture ADD prise_en_charge_manuelle BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE facture ADD taux_prise_en_charge_manuel INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture ADD organisme_prise_en_charge_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE866410B144DA86 FOREIGN KEY (organisme_prise_en_charge_id) REFERENCES organisme_prise_en_charge (id)');
        $this->addSql('CREATE INDEX IDX_FE866410B144DA86 ON facture (organisme_prise_en_charge_id)');
        $this->addSql('ALTER TABLE facture_ligne ADD montant_brut INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture_ligne ADD type_prestation_pec VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE facture_ligne ADD taux_prise_en_charge INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture_ligne ADD montant_prise_en_charge INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE facture_ligne ADD montant_patient INT DEFAULT 0 NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE convention_prise_en_charge DROP CONSTRAINT FK_1A0B6F1C5DDD38F5');
        $this->addSql('ALTER TABLE patient_couverture DROP CONSTRAINT FK_CAD57BEF6B899279');
        $this->addSql('ALTER TABLE patient_couverture DROP CONSTRAINT FK_CAD57BEF5DDD38F5');
        $this->addSql('DROP TABLE convention_prise_en_charge');
        $this->addSql('DROP TABLE organisme_prise_en_charge');
        $this->addSql('DROP TABLE patient_couverture');
        $this->addSql('ALTER TABLE facture DROP CONSTRAINT FK_FE866410B144DA86');
        $this->addSql('DROP INDEX IDX_FE866410B144DA86');
        $this->addSql('ALTER TABLE facture DROP montant_total_brut');
        $this->addSql('ALTER TABLE facture DROP montant_total_prise_en_charge');
        $this->addSql('ALTER TABLE facture DROP montant_total_patient');
        $this->addSql('ALTER TABLE facture DROP montant_paye_patient');
        $this->addSql('ALTER TABLE facture DROP reste_patient');
        $this->addSql('ALTER TABLE facture DROP prise_en_charge_active');
        $this->addSql('ALTER TABLE facture DROP prise_en_charge_manuelle');
        $this->addSql('ALTER TABLE facture DROP taux_prise_en_charge_manuel');
        $this->addSql('ALTER TABLE facture DROP organisme_prise_en_charge_id');
        $this->addSql('ALTER TABLE facture_ligne DROP montant_brut');
        $this->addSql('ALTER TABLE facture_ligne DROP type_prestation_pec');
        $this->addSql('ALTER TABLE facture_ligne DROP taux_prise_en_charge');
        $this->addSql('ALTER TABLE facture_ligne DROP montant_prise_en_charge');
        $this->addSql('ALTER TABLE facture_ligne DROP montant_patient');
    }
}
