<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260405130901 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administration_traitement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_administration DATE NOT NULL, heure SMALLINT NOT NULL, statut VARCHAR(20) NOT NULL, administre_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observation TEXT DEFAULT NULL, traitement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB5D3352DDA344B6 ON administration_traitement (traitement_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_traitement_date_heure ON administration_traitement (traitement_id, date_administration, heure)');
        $this->addSql('CREATE TABLE antecedent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3166BE7CF531F4C5 ON antecedent (hospitalisation_id)');
        $this->addSql('CREATE TABLE bon_examen (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_demande TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, token VARCHAR(64) NOT NULL, note TEXT DEFAULT NULL, consultation_id INT DEFAULT NULL, patient_id INT NOT NULL, medecin_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4530F7D65F37A13B ON bon_examen (token)');
        $this->addSql('CREATE INDEX IDX_4530F7D662FF6CDF ON bon_examen (consultation_id)');
        $this->addSql('CREATE INDEX IDX_4530F7D66B899279 ON bon_examen (patient_id)');
        $this->addSql('CREATE INDEX IDX_4530F7D64F31A84 ON bon_examen (medecin_id)');
        $this->addSql('CREATE TABLE bon_examen_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, urgence BOOLEAN DEFAULT NULL, note TEXT DEFAULT NULL, resultat_valeur VARCHAR(255) DEFAULT NULL, unite VARCHAR(50) DEFAULT NULL, valeurs_normales VARCHAR(255) DEFAULT NULL, resultat_texte TEXT DEFAULT NULL, resultat_saisi_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, piece_jointe_path VARCHAR(255) DEFAULT NULL, prix_unitaire NUMERIC(10, 2) DEFAULT NULL, bon_id INT NOT NULL, resultat_saisi_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65C1F3EAAD65737C ON bon_examen_ligne (bon_id)');
        $this->addSql('CREATE INDEX IDX_65C1F3EA7FF20340 ON bon_examen_ligne (resultat_saisi_par_id)');
        $this->addSql('CREATE TABLE bon_matiere (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero VARCHAR(50) NOT NULL, type VARCHAR(255) NOT NULL, motif VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, date_bon TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reference_externe VARCHAR(255) DEFAULT NULL, observation TEXT DEFAULT NULL, impact_stock BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ordonnateur_id INT DEFAULT NULL, cree_par_id INT DEFAULT NULL, vente_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_560CF280F55AE19E ON bon_matiere (numero)');
        $this->addSql('CREATE INDEX IDX_560CF28057F601D5 ON bon_matiere (ordonnateur_id)');
        $this->addSql('CREATE INDEX IDX_560CF280FC29C013 ON bon_matiere (cree_par_id)');
        $this->addSql('CREATE INDEX IDX_560CF2807DC7170A ON bon_matiere (vente_id)');
        $this->addSql('CREATE TABLE bon_matiere_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION DEFAULT NULL, observation TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, bon_id INT NOT NULL, medicament_id INT NOT NULL, lot_id INT DEFAULT NULL, vente_ligne_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_D36BCD40AD65737C ON bon_matiere_ligne (bon_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40AB0D61F7 ON bon_matiere_ligne (medicament_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40A8CBA5F7 ON bon_matiere_ligne (lot_id)');
        $this->addSql('CREATE INDEX IDX_D36BCD40FA166692 ON bon_matiere_ligne (vente_ligne_id)');
        $this->addSql('CREATE TABLE cim10_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, libelle VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, statut VARCHAR(255) NOT NULL, poids DOUBLE PRECISION DEFAULT NULL, taille DOUBLE PRECISION DEFAULT NULL, temperature DOUBLE PRECISION DEFAULT NULL, tension_arterielle VARCHAR(255) DEFAULT NULL, motifs TEXT DEFAULT NULL, diagnostic TEXT DEFAULT NULL, frequence_cardiaque INT DEFAULT NULL, histoire TEXT DEFAULT NULL, examen_clinique TEXT DEFAULT NULL, conduite_atenir TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medecin_id INT NOT NULL, dossier_medical_id INT NOT NULL, rendez_vous_id INT DEFAULT NULL, cim10_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_964685A64F31A84 ON consultation (medecin_id)');
        $this->addSql('CREATE INDEX IDX_964685A67750B79F ON consultation (dossier_medical_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_964685A691EF7EAA ON consultation (rendez_vous_id)');
        $this->addSql('CREATE INDEX IDX_964685A664681836 ON consultation (cim10_id)');
        $this->addSql('CREATE TABLE dossier_medical (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_dossier VARCHAR(50) NOT NULL, observations TEXT DEFAULT NULL, groupe_sanguin VARCHAR(10) DEFAULT NULL, allergies TEXT DEFAULT NULL, antecedents_medicaux TEXT DEFAULT NULL, antecedents_chirurgicaux TEXT DEFAULT NULL, maladies_chroniques TEXT DEFAULT NULL, traitement_en_cours TEXT DEFAULT NULL, handicap VARCHAR(255) DEFAULT NULL, grossesse BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3581EE62FB1CFE96 ON dossier_medical (numero_dossier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3581EE626B899279 ON dossier_medical (patient_id)');
        $this->addSql('CREATE TABLE examen_clinique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tension_arterielle VARCHAR(255) DEFAULT NULL, pouls INT DEFAULT NULL, temperature DOUBLE PRECISION DEFAULT NULL, saturation_oxygene DOUBLE PRECISION DEFAULT NULL, frequence_respiratoire INT DEFAULT NULL, poids DOUBLE PRECISION DEFAULT NULL, taille DOUBLE PRECISION DEFAULT NULL, imc DOUBLE PRECISION DEFAULT NULL, deshydratation BOOLEAN NOT NULL, oedeme BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E840F22F531F4C5 ON examen_clinique (hospitalisation_id)');
        $this->addSql('CREATE TABLE examen_complementaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, resultat TEXT DEFAULT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15CEF72DF531F4C5 ON examen_complementaire (hospitalisation_id)');
        $this->addSql('CREATE TABLE examen_neurologique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conscience VARCHAR(50) DEFAULT NULL, tonus_musculaire VARCHAR(255) DEFAULT NULL, force_membre_superieur_d INT DEFAULT NULL, force_membre_superieur_g INT DEFAULT NULL, force_membre_inferieur_d INT DEFAULT NULL, force_membre_inferieur_g INT DEFAULT NULL, babinski BOOLEAN NOT NULL, grasping BOOLEAN NOT NULL, aphasie_type VARCHAR(100) DEFAULT NULL, agnosie BOOLEAN NOT NULL, apraxie_type VARCHAR(100) DEFAULT NULL, trouble_sphincteriens VARCHAR(100) DEFAULT NULL, raideur_nuque BOOLEAN NOT NULL, brudzinski BOOLEAN NOT NULL, kernig BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_484F7486F531F4C5 ON examen_neurologique (hospitalisation_id)');
        $this->addSql('CREATE TABLE facture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant_total INT DEFAULT NULL, montant_paye INT DEFAULT NULL, reste_apayer INT DEFAULT NULL, date_emission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_paiement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE86641062FF6CDF ON facture (consultation_id)');
        $this->addSql('CREATE TABLE facture_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(180) NOT NULL, quantite INT NOT NULL, prix_unitaire INT NOT NULL, total INT NOT NULL, type VARCHAR(30) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facture_id INT NOT NULL, prescription_prestation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_C5C453347F2DEE08 ON facture_ligne (facture_id)');
        $this->addSql('CREATE INDEX IDX_C5C45334FD5FB388 ON facture_ligne (prescription_prestation_id)');
        $this->addSql('CREATE TABLE hospitalisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_admission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_sortie TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif_admission VARCHAR(255) NOT NULL, histoire_maladie TEXT DEFAULT NULL, evolution TEXT DEFAULT NULL, conclusion TEXT DEFAULT NULL, statut VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dossier_medical_id INT NOT NULL, medecin_referent_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67C059597750B79F ON hospitalisation (dossier_medical_id)');
        $this->addSql('CREATE INDEX IDX_67C05959533AC932 ON hospitalisation (medecin_referent_id)');
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_lot VARCHAR(100) DEFAULT NULL, date_peremption DATE DEFAULT NULL, quantite INT NOT NULL, prix_achat DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medicament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B81291BAB0D61F7 ON lot (medicament_id)');
        $this->addSql('CREATE TABLE medicament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, code_barre VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE paiement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant INT NOT NULL, mode VARCHAR(255) NOT NULL, paye_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, facture_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B1DC7A1E7F2DEE08 ON paiement (facture_id)');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, date_naissance DATE DEFAULT NULL, telephone VARCHAR(30) NOT NULL, code VARCHAR(30) NOT NULL, sexe VARCHAR(10) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, groupe_sanguin VARCHAR(10) DEFAULT NULL, emergency_contact_name VARCHAR(100) DEFAULT NULL, emergency_contact_relation VARCHAR(50) DEFAULT NULL, emergency_contact_phone VARCHAR(30) DEFAULT NULL, emergency_contact_address VARCHAR(255) DEFAULT NULL, taille DOUBLE PRECISION DEFAULT NULL, poids DOUBLE PRECISION DEFAULT NULL, allergies TEXT DEFAULT NULL, antecedents_medicaux TEXT DEFAULT NULL, antecedents_chirurgicaux TEXT DEFAULT NULL, maladies_chroniques TEXT DEFAULT NULL, traitement_en_cours TEXT DEFAULT NULL, handicap VARCHAR(255) DEFAULT NULL, grossesse BOOLEAN DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1ADAD7EB77153098 ON patient (code)');
        $this->addSql('CREATE TABLE prescription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_prescription VARCHAR(100) NOT NULL, instructions TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FBFB8D962FF6CDF ON prescription (consultation_id)');
        $this->addSql('CREATE TABLE prescription_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, posologie VARCHAR(255) NOT NULL, duree INT DEFAULT NULL, libelle VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prescription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A2583AC93DB413D ON prescription_ligne (prescription_id)');
        $this->addSql('CREATE TABLE prescription_prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, instructions TEXT DEFAULT NULL, statut VARCHAR(255) NOT NULL, a_facturer BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, tarif_prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9F64EED62FF6CDF ON prescription_prestation (consultation_id)');
        $this->addSql('CREATE INDEX IDX_E9F64EED97EFAB4B ON prescription_prestation (tarif_prestation_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, motif VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, medecin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A6B899279 ON rendez_vous (patient_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A4F31A84 ON rendez_vous (medecin_id)');
        $this->addSql('CREATE TABLE resultat_laboratoire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resultat TEXT DEFAULT NULL, conclusion TEXT DEFAULT NULL, date_validation TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, valide_par VARCHAR(150) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prescription_prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_743224F5FD5FB388 ON resultat_laboratoire (prescription_prestation_id)');
        $this->addSql('CREATE TABLE resultat_laboratoire_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, demande VARCHAR(255) NOT NULL, resultat TEXT DEFAULT NULL, valeur_normale TEXT DEFAULT NULL, ordre INT NOT NULL, resultat_laboratoire_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A50CC6D7EC71C459 ON resultat_laboratoire_ligne (resultat_laboratoire_id)');
        $this->addSql('CREATE TABLE service_medical (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B85F55C6A4D60759 ON service_medical (libelle)');
        $this->addSql('CREATE TABLE tarif_prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(180) NOT NULL, code VARCHAR(180) NOT NULL, categorie VARCHAR(255) NOT NULL, prix INT NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, description TEXT DEFAULT NULL, service_execution VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_258A4FA4D60759 ON tarif_prestation (libelle)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_258A4F77153098 ON tarif_prestation (code)');
        $this->addSql('CREATE TABLE traitement_hospitalisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, heures_administration JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8B90D58F531F4C5 ON traitement_hospitalisation (hospitalisation_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, roles JSON NOT NULL, force_password_change BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, service_medical_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3F85E0677 ON utilisateur (username)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3CF7BCA0E ON utilisateur (service_medical_id)');
        $this->addSql('CREATE TABLE vente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vendeur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_888A2A4C858C065E ON vente (vendeur_id)');
        $this->addSql('CREATE TABLE vente_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, vente_id INT NOT NULL, medicament_id INT NOT NULL, lot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43E1D6CA7DC7170A ON vente_ligne (vente_id)');
        $this->addSql('CREATE INDEX IDX_43E1D6CAAB0D61F7 ON vente_ligne (medicament_id)');
        $this->addSql('CREATE INDEX IDX_43E1D6CAA8CBA5F7 ON vente_ligne (lot_id)');
        $this->addSql('ALTER TABLE administration_traitement ADD CONSTRAINT FK_BB5D3352DDA344B6 FOREIGN KEY (traitement_id) REFERENCES traitement_hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE antecedent ADD CONSTRAINT FK_3166BE7CF531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D662FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D66B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen ADD CONSTRAINT FK_4530F7D64F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen_ligne ADD CONSTRAINT FK_65C1F3EAAD65737C FOREIGN KEY (bon_id) REFERENCES bon_examen (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_examen_ligne ADD CONSTRAINT FK_65C1F3EA7FF20340 FOREIGN KEY (resultat_saisi_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF28057F601D5 FOREIGN KEY (ordonnateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF280FC29C013 FOREIGN KEY (cree_par_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere ADD CONSTRAINT FK_560CF2807DC7170A FOREIGN KEY (vente_id) REFERENCES vente (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40AD65737C FOREIGN KEY (bon_id) REFERENCES bon_matiere (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40AB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE RESTRICT NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40A8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD CONSTRAINT FK_D36BCD40FA166692 FOREIGN KEY (vente_ligne_id) REFERENCES vente_ligne (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A67750B79F FOREIGN KEY (dossier_medical_id) REFERENCES dossier_medical (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A691EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A664681836 FOREIGN KEY (cim10_id) REFERENCES cim10_code (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier_medical ADD CONSTRAINT FK_3581EE626B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_clinique ADD CONSTRAINT FK_3E840F22F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_complementaire ADD CONSTRAINT FK_15CEF72DF531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_neurologique ADD CONSTRAINT FK_484F7486F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641062FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facture_ligne ADD CONSTRAINT FK_C5C453347F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facture_ligne ADD CONSTRAINT FK_C5C45334FD5FB388 FOREIGN KEY (prescription_prestation_id) REFERENCES prescription_prestation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospitalisation ADD CONSTRAINT FK_67C059597750B79F FOREIGN KEY (dossier_medical_id) REFERENCES dossier_medical (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospitalisation ADD CONSTRAINT FK_67C05959533AC932 FOREIGN KEY (medecin_referent_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE paiement ADD CONSTRAINT FK_B1DC7A1E7F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D962FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_ligne ADD CONSTRAINT FK_9A2583AC93DB413D FOREIGN KEY (prescription_id) REFERENCES prescription (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_prestation ADD CONSTRAINT FK_E9F64EED62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_prestation ADD CONSTRAINT FK_E9F64EED97EFAB4B FOREIGN KEY (tarif_prestation_id) REFERENCES tarif_prestation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A4F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat_laboratoire ADD CONSTRAINT FK_743224F5FD5FB388 FOREIGN KEY (prescription_prestation_id) REFERENCES prescription_prestation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat_laboratoire_ligne ADD CONSTRAINT FK_A50CC6D7EC71C459 FOREIGN KEY (resultat_laboratoire_id) REFERENCES resultat_laboratoire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE traitement_hospitalisation ADD CONSTRAINT FK_E8B90D58F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3CF7BCA0E FOREIGN KEY (service_medical_id) REFERENCES service_medical (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4C858C065E FOREIGN KEY (vendeur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CA7DC7170A FOREIGN KEY (vente_id) REFERENCES vente (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CAAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CAA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE administration_traitement DROP CONSTRAINT FK_BB5D3352DDA344B6');
        $this->addSql('ALTER TABLE antecedent DROP CONSTRAINT FK_3166BE7CF531F4C5');
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D662FF6CDF');
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D66B899279');
        $this->addSql('ALTER TABLE bon_examen DROP CONSTRAINT FK_4530F7D64F31A84');
        $this->addSql('ALTER TABLE bon_examen_ligne DROP CONSTRAINT FK_65C1F3EAAD65737C');
        $this->addSql('ALTER TABLE bon_examen_ligne DROP CONSTRAINT FK_65C1F3EA7FF20340');
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF28057F601D5');
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF280FC29C013');
        $this->addSql('ALTER TABLE bon_matiere DROP CONSTRAINT FK_560CF2807DC7170A');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40AD65737C');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40AB0D61F7');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40A8CBA5F7');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP CONSTRAINT FK_D36BCD40FA166692');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A64F31A84');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A67750B79F');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A691EF7EAA');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A664681836');
        $this->addSql('ALTER TABLE dossier_medical DROP CONSTRAINT FK_3581EE626B899279');
        $this->addSql('ALTER TABLE examen_clinique DROP CONSTRAINT FK_3E840F22F531F4C5');
        $this->addSql('ALTER TABLE examen_complementaire DROP CONSTRAINT FK_15CEF72DF531F4C5');
        $this->addSql('ALTER TABLE examen_neurologique DROP CONSTRAINT FK_484F7486F531F4C5');
        $this->addSql('ALTER TABLE facture DROP CONSTRAINT FK_FE86641062FF6CDF');
        $this->addSql('ALTER TABLE facture_ligne DROP CONSTRAINT FK_C5C453347F2DEE08');
        $this->addSql('ALTER TABLE facture_ligne DROP CONSTRAINT FK_C5C45334FD5FB388');
        $this->addSql('ALTER TABLE hospitalisation DROP CONSTRAINT FK_67C059597750B79F');
        $this->addSql('ALTER TABLE hospitalisation DROP CONSTRAINT FK_67C05959533AC932');
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BAB0D61F7');
        $this->addSql('ALTER TABLE paiement DROP CONSTRAINT FK_B1DC7A1E7F2DEE08');
        $this->addSql('ALTER TABLE prescription DROP CONSTRAINT FK_1FBFB8D962FF6CDF');
        $this->addSql('ALTER TABLE prescription_ligne DROP CONSTRAINT FK_9A2583AC93DB413D');
        $this->addSql('ALTER TABLE prescription_prestation DROP CONSTRAINT FK_E9F64EED62FF6CDF');
        $this->addSql('ALTER TABLE prescription_prestation DROP CONSTRAINT FK_E9F64EED97EFAB4B');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A6B899279');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A4F31A84');
        $this->addSql('ALTER TABLE resultat_laboratoire DROP CONSTRAINT FK_743224F5FD5FB388');
        $this->addSql('ALTER TABLE resultat_laboratoire_ligne DROP CONSTRAINT FK_A50CC6D7EC71C459');
        $this->addSql('ALTER TABLE traitement_hospitalisation DROP CONSTRAINT FK_E8B90D58F531F4C5');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3CF7BCA0E');
        $this->addSql('ALTER TABLE vente DROP CONSTRAINT FK_888A2A4C858C065E');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CA7DC7170A');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CAAB0D61F7');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CAA8CBA5F7');
        $this->addSql('DROP TABLE administration_traitement');
        $this->addSql('DROP TABLE antecedent');
        $this->addSql('DROP TABLE bon_examen');
        $this->addSql('DROP TABLE bon_examen_ligne');
        $this->addSql('DROP TABLE bon_matiere');
        $this->addSql('DROP TABLE bon_matiere_ligne');
        $this->addSql('DROP TABLE cim10_code');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE dossier_medical');
        $this->addSql('DROP TABLE examen_clinique');
        $this->addSql('DROP TABLE examen_complementaire');
        $this->addSql('DROP TABLE examen_neurologique');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE facture_ligne');
        $this->addSql('DROP TABLE hospitalisation');
        $this->addSql('DROP TABLE lot');
        $this->addSql('DROP TABLE medicament');
        $this->addSql('DROP TABLE paiement');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE prescription');
        $this->addSql('DROP TABLE prescription_ligne');
        $this->addSql('DROP TABLE prescription_prestation');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE resultat_laboratoire');
        $this->addSql('DROP TABLE resultat_laboratoire_ligne');
        $this->addSql('DROP TABLE service_medical');
        $this->addSql('DROP TABLE tarif_prestation');
        $this->addSql('DROP TABLE traitement_hospitalisation');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE vente');
        $this->addSql('DROP TABLE vente_ligne');
    }
}
