<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260224133149 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE antecedent (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3166BE7CF531F4C5 ON antecedent (hospitalisation_id)');
        $this->addSql('CREATE TABLE consultation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, poids DOUBLE PRECISION DEFAULT NULL, taille DOUBLE PRECISION DEFAULT NULL, temperature DOUBLE PRECISION DEFAULT NULL, tension_arterielle VARCHAR(255) DEFAULT NULL, motifs TEXT DEFAULT NULL, diagnostic TEXT DEFAULT NULL, frequence_cardiaque INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medecin_id INT NOT NULL, dossier_medical_id INT NOT NULL, rendez_vous_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_964685A64F31A84 ON consultation (medecin_id)');
        $this->addSql('CREATE INDEX IDX_964685A67750B79F ON consultation (dossier_medical_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_964685A691EF7EAA ON consultation (rendez_vous_id)');
        $this->addSql('CREATE TABLE dossier_medical (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_dossier VARCHAR(50) NOT NULL, observations TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3581EE62FB1CFE96 ON dossier_medical (numero_dossier)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3581EE626B899279 ON dossier_medical (patient_id)');
        $this->addSql('CREATE TABLE examen_clinique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tension_arterielle VARCHAR(255) DEFAULT NULL, pouls INT DEFAULT NULL, temperature DOUBLE PRECISION DEFAULT NULL, saturation_oxygene DOUBLE PRECISION DEFAULT NULL, frequence_respiratoire INT DEFAULT NULL, poids DOUBLE PRECISION DEFAULT NULL, taille DOUBLE PRECISION DEFAULT NULL, imc DOUBLE PRECISION DEFAULT NULL, deshydratation BOOLEAN NOT NULL, oedeme BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3E840F22F531F4C5 ON examen_clinique (hospitalisation_id)');
        $this->addSql('CREATE TABLE examen_complementaire (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, resultat TEXT DEFAULT NULL, date_examen TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15CEF72DF531F4C5 ON examen_complementaire (hospitalisation_id)');
        $this->addSql('CREATE TABLE examen_neurologique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conscience VARCHAR(50) DEFAULT NULL, tonus_musculaire VARCHAR(255) DEFAULT NULL, force_membre_superieur_d INT DEFAULT NULL, force_membre_superieur_g INT DEFAULT NULL, force_membre_inferieur_d INT DEFAULT NULL, force_membre_inferieur_g INT DEFAULT NULL, babinski BOOLEAN NOT NULL, grasping BOOLEAN NOT NULL, aphasie_type VARCHAR(100) DEFAULT NULL, agnosie BOOLEAN NOT NULL, apraxie_type VARCHAR(100) DEFAULT NULL, trouble_sphincteriens VARCHAR(100) DEFAULT NULL, raideur_nuque BOOLEAN NOT NULL, brudzinski BOOLEAN NOT NULL, kernig BOOLEAN NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_484F7486F531F4C5 ON examen_neurologique (hospitalisation_id)');
        $this->addSql('CREATE TABLE facture (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, montant DOUBLE PRECISION NOT NULL, date_emission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_paiement TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, statut_paiement VARCHAR(255) NOT NULL, mode_paiement VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE86641062FF6CDF ON facture (consultation_id)');
        $this->addSql('CREATE TABLE hospitalisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_admission TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, date_sortie TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, motif_admission VARCHAR(255) NOT NULL, histoire_maladie TEXT DEFAULT NULL, evolution TEXT DEFAULT NULL, conclusion TEXT DEFAULT NULL, statut VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dossier_medical_id INT NOT NULL, medecin_referent_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_67C059597750B79F ON hospitalisation (dossier_medical_id)');
        $this->addSql('CREATE INDEX IDX_67C05959533AC932 ON hospitalisation (medecin_referent_id)');
        $this->addSql('CREATE TABLE patient (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, date_naissance DATE DEFAULT NULL, telephone VARCHAR(30) NOT NULL, code VARCHAR(30) NOT NULL, sexe VARCHAR(10) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, groupe_sanguin VARCHAR(10) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1ADAD7EB77153098 ON patient (code)');
        $this->addSql('CREATE TABLE prescription (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_prescription VARCHAR(100) NOT NULL, instructions TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1FBFB8D962FF6CDF ON prescription (consultation_id)');
        $this->addSql('CREATE TABLE prescription_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, posologie VARCHAR(255) NOT NULL, duree INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, prescription_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9A2583AC93DB413D ON prescription_ligne (prescription_id)');
        $this->addSql('CREATE TABLE rendez_vous (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_heure TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, statut VARCHAR(255) NOT NULL, motif VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, patient_id INT NOT NULL, medecin_id INT NOT NULL, consultation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_65E8AA0A6B899279 ON rendez_vous (patient_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A4F31A84 ON rendez_vous (medecin_id)');
        $this->addSql('CREATE INDEX IDX_65E8AA0A62FF6CDF ON rendez_vous (consultation_id)');
        $this->addSql('CREATE TABLE service_medical (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(150) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE traitement_hospitalisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, description TEXT NOT NULL, date_debut TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, date_fin TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, hospitalisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8B90D58F531F4C5 ON traitement_hospitalisation (hospitalisation_id)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, username VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, statut VARCHAR(255) NOT NULL, roles JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, service_medical_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3F85E0677 ON utilisateur (username)');
        $this->addSql('CREATE INDEX IDX_1D1C63B3CF7BCA0E ON utilisateur (service_medical_id)');
        $this->addSql('ALTER TABLE antecedent ADD CONSTRAINT FK_3166BE7CF531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A64F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A67750B79F FOREIGN KEY (dossier_medical_id) REFERENCES dossier_medical (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A691EF7EAA FOREIGN KEY (rendez_vous_id) REFERENCES rendez_vous (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dossier_medical ADD CONSTRAINT FK_3581EE626B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_clinique ADD CONSTRAINT FK_3E840F22F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_complementaire ADD CONSTRAINT FK_15CEF72DF531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_neurologique ADD CONSTRAINT FK_484F7486F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE facture ADD CONSTRAINT FK_FE86641062FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospitalisation ADD CONSTRAINT FK_67C059597750B79F FOREIGN KEY (dossier_medical_id) REFERENCES dossier_medical (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE hospitalisation ADD CONSTRAINT FK_67C05959533AC932 FOREIGN KEY (medecin_referent_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription ADD CONSTRAINT FK_1FBFB8D962FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_ligne ADD CONSTRAINT FK_9A2583AC93DB413D FOREIGN KEY (prescription_id) REFERENCES prescription (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A4F31A84 FOREIGN KEY (medecin_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE rendez_vous ADD CONSTRAINT FK_65E8AA0A62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE traitement_hospitalisation ADD CONSTRAINT FK_E8B90D58F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B3CF7BCA0E FOREIGN KEY (service_medical_id) REFERENCES service_medical (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE antecedent DROP CONSTRAINT FK_3166BE7CF531F4C5');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A64F31A84');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A67750B79F');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A691EF7EAA');
        $this->addSql('ALTER TABLE dossier_medical DROP CONSTRAINT FK_3581EE626B899279');
        $this->addSql('ALTER TABLE examen_clinique DROP CONSTRAINT FK_3E840F22F531F4C5');
        $this->addSql('ALTER TABLE examen_complementaire DROP CONSTRAINT FK_15CEF72DF531F4C5');
        $this->addSql('ALTER TABLE examen_neurologique DROP CONSTRAINT FK_484F7486F531F4C5');
        $this->addSql('ALTER TABLE facture DROP CONSTRAINT FK_FE86641062FF6CDF');
        $this->addSql('ALTER TABLE hospitalisation DROP CONSTRAINT FK_67C059597750B79F');
        $this->addSql('ALTER TABLE hospitalisation DROP CONSTRAINT FK_67C05959533AC932');
        $this->addSql('ALTER TABLE prescription DROP CONSTRAINT FK_1FBFB8D962FF6CDF');
        $this->addSql('ALTER TABLE prescription_ligne DROP CONSTRAINT FK_9A2583AC93DB413D');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A6B899279');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A4F31A84');
        $this->addSql('ALTER TABLE rendez_vous DROP CONSTRAINT FK_65E8AA0A62FF6CDF');
        $this->addSql('ALTER TABLE traitement_hospitalisation DROP CONSTRAINT FK_E8B90D58F531F4C5');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B3CF7BCA0E');
        $this->addSql('DROP TABLE antecedent');
        $this->addSql('DROP TABLE consultation');
        $this->addSql('DROP TABLE dossier_medical');
        $this->addSql('DROP TABLE examen_clinique');
        $this->addSql('DROP TABLE examen_complementaire');
        $this->addSql('DROP TABLE examen_neurologique');
        $this->addSql('DROP TABLE facture');
        $this->addSql('DROP TABLE hospitalisation');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE prescription');
        $this->addSql('DROP TABLE prescription_ligne');
        $this->addSql('DROP TABLE rendez_vous');
        $this->addSql('DROP TABLE service_medical');
        $this->addSql('DROP TABLE traitement_hospitalisation');
        $this->addSql('DROP TABLE utilisateur');
    }
}
