<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313143212 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administration_traitement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_administration DATE NOT NULL, heure SMALLINT NOT NULL, statut VARCHAR(20) NOT NULL, administre_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observation TEXT DEFAULT NULL, traitement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB5D3352DDA344B6 ON administration_traitement (traitement_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_traitement_date_heure ON administration_traitement (traitement_id, date_administration, heure)');
        $this->addSql('CREATE TABLE prescription_prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, instructions TEXT DEFAULT NULL, statut VARCHAR(255) NOT NULL, a_facturer BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, consultation_id INT NOT NULL, tarif_prestation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E9F64EED62FF6CDF ON prescription_prestation (consultation_id)');
        $this->addSql('CREATE INDEX IDX_E9F64EED97EFAB4B ON prescription_prestation (tarif_prestation_id)');
        $this->addSql('CREATE TABLE tarif_prestation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(180) NOT NULL, code VARCHAR(180) NOT NULL, categorie VARCHAR(255) NOT NULL, prix INT NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, description TEXT DEFAULT NULL, service_execution VARCHAR(50) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_258A4FA4D60759 ON tarif_prestation (libelle)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_258A4F77153098 ON tarif_prestation (code)');
        $this->addSql('ALTER TABLE administration_traitement ADD CONSTRAINT FK_BB5D3352DDA344B6 FOREIGN KEY (traitement_id) REFERENCES traitement_hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_prestation ADD CONSTRAINT FK_E9F64EED62FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE prescription_prestation ADD CONSTRAINT FK_E9F64EED97EFAB4B FOREIGN KEY (tarif_prestation_id) REFERENCES tarif_prestation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE acte_realise DROP CONSTRAINT fk_ece410b262ff6cdf');
        $this->addSql('ALTER TABLE examen_demande DROP CONSTRAINT fk_8514b0817ff20340');
        $this->addSql('ALTER TABLE examen_demande DROP CONSTRAINT fk_8514b08162ff6cdf');
        $this->addSql('DROP TABLE acte_realise');
        $this->addSql('DROP TABLE examen_demande');
        $this->addSql('ALTER TABLE consultation ALTER rendez_vous_id DROP NOT NULL');
        $this->addSql('ALTER TABLE facture ADD montant_total INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture ADD montant_paye INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture ADD reste_apayer INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture DROP montant');
        $this->addSql('ALTER TABLE facture DROP mode_paiement');
        $this->addSql('ALTER TABLE facture RENAME COLUMN statut_paiement TO statut');
        $this->addSql('ALTER TABLE facture_ligne ADD prescription_prestation_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE facture_ligne ADD CONSTRAINT FK_C5C45334FD5FB388 FOREIGN KEY (prescription_prestation_id) REFERENCES prescription_prestation (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_C5C45334FD5FB388 ON facture_ligne (prescription_prestation_id)');
        $this->addSql('ALTER TABLE paiement ALTER mode TYPE VARCHAR(255)');
        $this->addSql('ALTER TABLE traitement_hospitalisation ADD heures_administration JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acte_realise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(10, 2) DEFAULT NULL, note TEXT DEFAULT NULL, consultation_id INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ece410b262ff6cdf ON acte_realise (consultation_id)');
        $this->addSql('CREATE TABLE examen_demande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, urgence BOOLEAN DEFAULT NULL, statut VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, consultation_id INT NOT NULL, prix_unitaire NUMERIC(10, 2) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resultat_texte TEXT DEFAULT NULL, resultat_saisi_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, resultat_saisi_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_8514b08162ff6cdf ON examen_demande (consultation_id)');
        $this->addSql('CREATE INDEX idx_8514b0817ff20340 ON examen_demande (resultat_saisi_par_id)');
        $this->addSql('ALTER TABLE acte_realise ADD CONSTRAINT fk_ece410b262ff6cdf FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE examen_demande ADD CONSTRAINT fk_8514b0817ff20340 FOREIGN KEY (resultat_saisi_par_id) REFERENCES utilisateur (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE examen_demande ADD CONSTRAINT fk_8514b08162ff6cdf FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE administration_traitement DROP CONSTRAINT FK_BB5D3352DDA344B6');
        $this->addSql('ALTER TABLE prescription_prestation DROP CONSTRAINT FK_E9F64EED62FF6CDF');
        $this->addSql('ALTER TABLE prescription_prestation DROP CONSTRAINT FK_E9F64EED97EFAB4B');
        $this->addSql('DROP TABLE administration_traitement');
        $this->addSql('DROP TABLE prescription_prestation');
        $this->addSql('DROP TABLE tarif_prestation');
        $this->addSql('ALTER TABLE consultation ALTER rendez_vous_id SET NOT NULL');
        $this->addSql('ALTER TABLE facture ADD montant DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE facture ADD mode_paiement VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE facture DROP montant_total');
        $this->addSql('ALTER TABLE facture DROP montant_paye');
        $this->addSql('ALTER TABLE facture DROP reste_apayer');
        $this->addSql('ALTER TABLE facture RENAME COLUMN statut TO statut_paiement');
        $this->addSql('ALTER TABLE facture_ligne DROP CONSTRAINT FK_C5C45334FD5FB388');
        $this->addSql('DROP INDEX IDX_C5C45334FD5FB388');
        $this->addSql('ALTER TABLE facture_ligne DROP prescription_prestation_id');
        $this->addSql('ALTER TABLE paiement ALTER mode TYPE VARCHAR(20)');
        $this->addSql('ALTER TABLE traitement_hospitalisation DROP heures_administration');
    }
}
