<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260303130252 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE acte_realise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, quantite INT NOT NULL, prix_unitaire NUMERIC(10, 2) DEFAULT NULL, note TEXT DEFAULT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_ECE410B262FF6CDF ON acte_realise (consultation_id)');
        $this->addSql('CREATE TABLE cim10_code (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(10) NOT NULL, libelle VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE examen_demande (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(255) NOT NULL, urgence BOOLEAN DEFAULT NULL, statut VARCHAR(255) NOT NULL, note TEXT DEFAULT NULL, consultation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8514B08162FF6CDF ON examen_demande (consultation_id)');
        $this->addSql('ALTER TABLE acte_realise ADD CONSTRAINT FK_ECE410B262FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE examen_demande ADD CONSTRAINT FK_8514B08162FF6CDF FOREIGN KEY (consultation_id) REFERENCES consultation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE consultation ADD statut VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD histoire TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ADD examen_clinique TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ADD conduite_atenir TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ADD cim10_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE consultation ALTER rendez_vous_id SET NOT NULL');
        $this->addSql('ALTER TABLE consultation ADD CONSTRAINT FK_964685A664681836 FOREIGN KEY (cim10_id) REFERENCES cim10_code (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_964685A664681836 ON consultation (cim10_id)');
        $this->addSql('ALTER TABLE service_medical ALTER libelle TYPE VARCHAR(255)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B85F55C6A4D60759 ON service_medical (libelle)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE acte_realise DROP CONSTRAINT FK_ECE410B262FF6CDF');
        $this->addSql('ALTER TABLE examen_demande DROP CONSTRAINT FK_8514B08162FF6CDF');
        $this->addSql('DROP TABLE acte_realise');
        $this->addSql('DROP TABLE cim10_code');
        $this->addSql('DROP TABLE examen_demande');
        $this->addSql('ALTER TABLE consultation DROP CONSTRAINT FK_964685A664681836');
        $this->addSql('DROP INDEX IDX_964685A664681836');
        $this->addSql('ALTER TABLE consultation DROP statut');
        $this->addSql('ALTER TABLE consultation DROP histoire');
        $this->addSql('ALTER TABLE consultation DROP examen_clinique');
        $this->addSql('ALTER TABLE consultation DROP conduite_atenir');
        $this->addSql('ALTER TABLE consultation DROP cim10_id');
        $this->addSql('ALTER TABLE consultation ALTER rendez_vous_id DROP NOT NULL');
        $this->addSql('DROP INDEX UNIQ_B85F55C6A4D60759');
        $this->addSql('ALTER TABLE service_medical ALTER libelle TYPE VARCHAR(150)');
    }
}
