<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260527001521 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE antibiotique (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, famille VARCHAR(100) DEFAULT NULL, est_actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE germe (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, est_actif BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5B3667726C6E55B5 ON germe (nom)');
        $this->addSql('CREATE TABLE resultat_antibiogramme (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numeration VARCHAR(255) DEFAULT NULL, commentaire TEXT DEFAULT NULL, resultat_laboratoire_id INT NOT NULL, germe_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2A5F8ADEEC71C459 ON resultat_antibiogramme (resultat_laboratoire_id)');
        $this->addSql('CREATE INDEX IDX_2A5F8ADED43211AC ON resultat_antibiogramme (germe_id)');
        $this->addSql('CREATE TABLE resultat_antibiogramme_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sensibilite VARCHAR(50) DEFAULT NULL, resultat_antibiogramme_id INT NOT NULL, antibiotique_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A81E3EB1DBEEE184 ON resultat_antibiogramme_ligne (resultat_antibiogramme_id)');
        $this->addSql('CREATE INDEX IDX_A81E3EB150F6756C ON resultat_antibiogramme_ligne (antibiotique_id)');
        $this->addSql('ALTER TABLE resultat_antibiogramme ADD CONSTRAINT FK_2A5F8ADEEC71C459 FOREIGN KEY (resultat_laboratoire_id) REFERENCES resultat_laboratoire (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat_antibiogramme ADD CONSTRAINT FK_2A5F8ADED43211AC FOREIGN KEY (germe_id) REFERENCES germe (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat_antibiogramme_ligne ADD CONSTRAINT FK_A81E3EB1DBEEE184 FOREIGN KEY (resultat_antibiogramme_id) REFERENCES resultat_antibiogramme (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resultat_antibiogramme_ligne ADD CONSTRAINT FK_A81E3EB150F6756C FOREIGN KEY (antibiotique_id) REFERENCES antibiotique (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resultat_antibiogramme DROP CONSTRAINT FK_2A5F8ADEEC71C459');
        $this->addSql('ALTER TABLE resultat_antibiogramme DROP CONSTRAINT FK_2A5F8ADED43211AC');
        $this->addSql('ALTER TABLE resultat_antibiogramme_ligne DROP CONSTRAINT FK_A81E3EB1DBEEE184');
        $this->addSql('ALTER TABLE resultat_antibiogramme_ligne DROP CONSTRAINT FK_A81E3EB150F6756C');
        $this->addSql('DROP TABLE antibiotique');
        $this->addSql('DROP TABLE germe');
        $this->addSql('DROP TABLE resultat_antibiogramme');
        $this->addSql('DROP TABLE resultat_antibiogramme_ligne');
    }
}
