<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260529142233 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE mouvement_stock (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(50) NOT NULL, quantite INT NOT NULL, valeur_achat_unitaire DOUBLE PRECISION DEFAULT NULL, operateur VARCHAR(150) DEFAULT NULL, reference_document VARCHAR(255) DEFAULT NULL, motif TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medicament_id INT NOT NULL, lot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_61E2C8EBAB0D61F7 ON mouvement_stock (medicament_id)');
        $this->addSql('CREATE INDEX IDX_61E2C8EBA8CBA5F7 ON mouvement_stock (lot_id)');
        $this->addSql('ALTER TABLE mouvement_stock ADD CONSTRAINT FK_61E2C8EBAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mouvement_stock ADD CONSTRAINT FK_61E2C8EBA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX idx_560cf2807dc7170a');
        $this->addSql('ALTER TABLE bon_matiere DROP vente_id');
        $this->addSql('DROP INDEX idx_d36bcd40fa166692');
        $this->addSql('ALTER TABLE bon_matiere_ligne DROP vente_ligne_id');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE mouvement_stock DROP CONSTRAINT FK_61E2C8EBAB0D61F7');
        $this->addSql('ALTER TABLE mouvement_stock DROP CONSTRAINT FK_61E2C8EBA8CBA5F7');
        $this->addSql('DROP TABLE mouvement_stock');
        $this->addSql('ALTER TABLE bon_matiere ADD vente_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_560cf2807dc7170a ON bon_matiere (vente_id)');
        $this->addSql('ALTER TABLE bon_matiere_ligne ADD vente_ligne_id INT DEFAULT NULL');
        $this->addSql('CREATE INDEX idx_d36bcd40fa166692 ON bon_matiere_ligne (vente_ligne_id)');
    }
}
