<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260723142147 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE honoraire_medecin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_acte DATE NOT NULL, nom_patient VARCHAR(255) DEFAULT NULL, libelle_acte VARCHAR(255) NOT NULL, montant_total DOUBLE PRECISION NOT NULL, taux_reversement DOUBLE PRECISION NOT NULL, montant_brut_medecin DOUBLE PRECISION NOT NULL, montant_isb DOUBLE PRECISION NOT NULL, montant_net_apayer DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medecin_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_328BD8504F31A84 ON honoraire_medecin (medecin_id)');
        $this->addSql('CREATE TABLE journal_caisse (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_operation DATE NOT NULL, libelle VARCHAR(255) NOT NULL, montant DOUBLE PRECISION NOT NULL, type_operation VARCHAR(50) NOT NULL, categorie VARCHAR(255) DEFAULT NULL, piece_justificative VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE medecin (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom_complet VARCHAR(255) NOT NULL, specialite VARCHAR(255) DEFAULT NULL, taux_isb_defaut DOUBLE PRECISION DEFAULT NULL, contact VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('ALTER TABLE honoraire_medecin ADD CONSTRAINT FK_328BD8504F31A84 FOREIGN KEY (medecin_id) REFERENCES medecin (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE honoraire_medecin DROP CONSTRAINT FK_328BD8504F31A84');
        $this->addSql('DROP TABLE honoraire_medecin');
        $this->addSql('DROP TABLE journal_caisse');
        $this->addSql('DROP TABLE medecin');
    }
}
