<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260311115628 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administration_traitement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date_administration DATE NOT NULL, heure SMALLINT NOT NULL, statut VARCHAR(20) NOT NULL, administre_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observation TEXT DEFAULT NULL, traitement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BB5D3352DDA344B6 ON administration_traitement (traitement_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_traitement_date_heure ON administration_traitement (traitement_id, date_administration, heure)');
        $this->addSql('ALTER TABLE administration_traitement ADD CONSTRAINT FK_BB5D3352DDA344B6 FOREIGN KEY (traitement_id) REFERENCES traitement_hospitalisation (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE administration_traitement DROP CONSTRAINT FK_BB5D3352DDA344B6');
        $this->addSql('DROP TABLE administration_traitement');
    }
}
