<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260310102422 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE lot (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_lot VARCHAR(100) DEFAULT NULL, date_peremption DATE DEFAULT NULL, quantite INT NOT NULL, prix_achat DOUBLE PRECISION DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, medicament_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B81291BAB0D61F7 ON lot (medicament_id)');
        $this->addSql('CREATE TABLE medicament (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, sku VARCHAR(100) DEFAULT NULL, code_barre VARCHAR(100) DEFAULT NULL, description TEXT DEFAULT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE vente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total DOUBLE PRECISION NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modified_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, vendeur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_888A2A4C858C065E ON vente (vendeur_id)');
        $this->addSql('CREATE TABLE vente_ligne (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quantite INT NOT NULL, prix_unitaire DOUBLE PRECISION NOT NULL, vente_id INT NOT NULL, medicament_id INT NOT NULL, lot_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_43E1D6CA7DC7170A ON vente_ligne (vente_id)');
        $this->addSql('CREATE INDEX IDX_43E1D6CAAB0D61F7 ON vente_ligne (medicament_id)');
        $this->addSql('CREATE INDEX IDX_43E1D6CAA8CBA5F7 ON vente_ligne (lot_id)');
        $this->addSql('ALTER TABLE lot ADD CONSTRAINT FK_B81291BAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente ADD CONSTRAINT FK_888A2A4C858C065E FOREIGN KEY (vendeur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CA7DC7170A FOREIGN KEY (vente_id) REFERENCES vente (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CAAB0D61F7 FOREIGN KEY (medicament_id) REFERENCES medicament (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vente_ligne ADD CONSTRAINT FK_43E1D6CAA8CBA5F7 FOREIGN KEY (lot_id) REFERENCES lot (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE lot DROP CONSTRAINT FK_B81291BAB0D61F7');
        $this->addSql('ALTER TABLE vente DROP CONSTRAINT FK_888A2A4C858C065E');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CA7DC7170A');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CAAB0D61F7');
        $this->addSql('ALTER TABLE vente_ligne DROP CONSTRAINT FK_43E1D6CAA8CBA5F7');
        $this->addSql('DROP TABLE lot');
        $this->addSql('DROP TABLE medicament');
        $this->addSql('DROP TABLE vente');
        $this->addSql('DROP TABLE vente_ligne');
    }
}
