<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260525192337 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE observation_medicale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contenu TEXT NOT NULL, type_observation VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, dossier_id INT NOT NULL, medecin_auteur_id INT NOT NULL, hospitalisation_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E50FDD60611C0C56 ON observation_medicale (dossier_id)');
        $this->addSql('CREATE INDEX IDX_E50FDD60E15D6F4E ON observation_medicale (medecin_auteur_id)');
        $this->addSql('CREATE INDEX IDX_E50FDD60F531F4C5 ON observation_medicale (hospitalisation_id)');
        $this->addSql('ALTER TABLE observation_medicale ADD CONSTRAINT FK_E50FDD60611C0C56 FOREIGN KEY (dossier_id) REFERENCES dossier_medical (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE observation_medicale ADD CONSTRAINT FK_E50FDD60E15D6F4E FOREIGN KEY (medecin_auteur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE observation_medicale ADD CONSTRAINT FK_E50FDD60F531F4C5 FOREIGN KEY (hospitalisation_id) REFERENCES hospitalisation (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE observation_medicale DROP CONSTRAINT FK_E50FDD60611C0C56');
        $this->addSql('ALTER TABLE observation_medicale DROP CONSTRAINT FK_E50FDD60E15D6F4E');
        $this->addSql('ALTER TABLE observation_medicale DROP CONSTRAINT FK_E50FDD60F531F4C5');
        $this->addSql('DROP TABLE observation_medicale');
    }
}
